#:schema node_modules/wrangler/config-schema.json
name = "vpn-url-change"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "5e47b1edab92412cae9f46038c89227d" }
]

[assets]
directory = "./public"
